### ISSUE TITLE
Auth.requestToken(): `input` must not start with a slash when using `prefixUrl`

### ISSUE THREAD

**Issue by mariesta** [ably-labs/react-hooks#8] opened 2022-03-14 12:56 UTC
# Context
I have installed `ably-labs/react-hooks` in order to use the configureAbly() and useChannel hook in My Next.js app. I created an API endpoint for authentication:
```
import Ably from "ably/promises";

export default async function handler(req, res) {
    const client = new Ably.Realtime(process.env.ABLY_API_KEY);
    const tokenRequestData = await client.auth.createTokenRequest({ clientId: 'ably-blog-app' });
    res.status(200).json(tokenRequestData);
};
```

And called `configureAbly` in my component:
```
configureAbly({ authUrl: '/api/createTokenRequest' });
```

It works fine apart from the fact that I get log messages in my server:
```
Ably: Auth.requestToken(): token request signing call returned error; err = Error: `input` must not start with a slash when using `prefixUrl`
```
I have tried removing the slash (this causes an issue) and I have moved the `configureAbly` in various places (inside a component, in `_app.js`), but it still appears. There is a new one every 30 seconds. Any idea what might cause it?

**Comment by retsamboon** [comment] 2022-05-26 04:30
I am seeing the same error and after doing some digging, I found that this is caused by a bug in the Ably dependency `got` v11.8.2 npm package. This bug seems to have been fixed by https://github.com/sindresorhus/got/pull/1667 (released in Got 12).

**Comment by starlight-akouri** [comment] 2023-05-22 19:26
@thisisjofrank I don't think your solution solves this problem. I am also still struggling with the same exact symptoms as the OP, but my got version is `"^11.8.5",`. I am wondering if I should manually set this to ^12?

**Comment by oleg131** [comment] 2023-06-26 00:14
I am having the same issue. Currently, the only solution is to manually modify the authUrl to be absolute (which would be different e.g. in dev and prod)

**Comment by WillSmithTE** [comment] 2023-07-03 17:40
Yeah this is annoying, @thisisjofrank should this really be closed?

**Comment by thisisjofrank** [comment] 2023-07-03 20:59
I'm afraid I no longer work on this product. Please email DevRel@ably.com to get some eyes on it.

**Comment by stmoreau** [comment] 2023-08-19 12:23
We understand this issue may have been closed while the fix for it was not working. Apologies about that, I have now re-opened the issue and we will look into it in the next week.

**Comment by owenpearson** [comment] 2023-08-29 13:06
Hey all, thanks for raising this issue with us!

This error message actually comes from `got` which is the HTTP client used by Ably when used in NodeJS. The error message itself is caused by `got` not being able to make an HTTP request to a URL which starts with a `/` (which makes sense really, in NodeJS there's no `window.location` or anything, so there's no obvious way to resolve a path without an explicit host name or scheme).

The real problem if you're seeing this issue, is that your NextJS application is creating an Ably client on the server side (ie in a NodeJS process) but really the Ably client should only be created on the client side. In my experience, the best way to ensure that this never happens is to wrap components which contain client-only code in a `next/dynamic` in order to force them to load on the client side, here's a simple example of how to do that:

```tsx
import dynamic from 'next/dynamic';

const DynamicAblyComponent = dynamic(() => import('./path/to/your/ably/component'), {
  ssr: false, // this ensures that server side rendering is never used for this component
})

export default DynamicAblyComponent;
```

If the above solution doesn't work for you, there are a few alternatives documented [here](https://github.com/vercel/next.js/discussions/42319#discussioncomment-4061453).

It's worth mentioning also that, while the name 'Client Components' (ie components with the `'use client'` directive) implies that these components will only be rendered on the client side, [NextJS may still run the component code on the server in order to pre-render HTML](https://nextjs.org/docs/app/building-your-application/rendering/client-components#how-are-client-components-rendered) so you may still need to use dynamic loading in order to avoid Ably clients being created on the server side.

I hope this clears things up, please let us know here if you have any further questions 🙂

**Closed by owenpearson** 2023-08-29 13:06 UTC

**Comment by starlight-akouri** [comment] 2023-08-31 21:13
There is something more dastardly going on here that really underscores the importance of using dynamic import for your client-side ably.  If you are seeing phantom connections/subscribers on your ably dashboard this could be the reason why.
When I switched to using next/dynamic, I saw that my "max connections" was not linearly increasing.

I am still trying to figure out how to export my `Realtime` client directly using this next/dynamic realm without having to create a custom component for each use case I want to connect client-side.

**Comment by sikula** [comment] 2023-09-10 22:00
@starlight-akouri Let me know if you find a solution.  I'm using Remix and it doesn't have dynamic function like nextjs, so I'm running into a similar issue as you I think.

**Comment by owenpearson** [comment] 2023-09-19 17:49
@starlight-akouri, I'm sorry to hear that you're still having issues here. It sounds like something in your application code is creating more ably-js clients than it should, but it's hard to say what the issue is without seeing some code. If you're able to share a repro I'd be happy to take a look?

**Comment by abdullinmx** [comment] 2023-10-07 16:19
@sikula, fyi I'm using Remix.run and it works fine with `configureAbly` hook. I've just wrapped it into a custom hook and ugly check for `window`

```

const useRTS = () => {
  const [configured, setConfigured] = useState(false);
  const hasWindow = typeof window !== 'undefined';
  useEffect(() => {
    if (hasWindow && !configured) {
      configureAbly({ authUrl: '/api/token' });
      setConfigured(true);
    }
  }, [hasWindow, configured]);
};

export default useRTS;

```
